ministryofjustice/court-case-matcher

src/main/java/uk/gov/justice/probation/courtcasematcher/controller/PingEndpoint.java
Allows Cross-origin resource sharingCross-origin resource sharing on /ping endpoint so that health check can be hit from Frontend code (such as build radiator).
=> CORS support

build.gradle, src/main/java/uk/gov/justice/probation/courtcasematcher/model/courtcaseservice/CourtCase.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/courtcaseservice/GroupedOffenderMatches.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/courtcaseservice/MatchIdentifiers.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/courtcaseservice/OffenderMatch.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapper.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/offendersearch/MatchType.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/offendersearch/OffenderSearchMatchType.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/offendersearch/SearchResponse.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClient.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/MatcherService.java, src/main/resources/application-dev.yml, src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapperTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchResponseRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/MatcherServiceTest.java, src/test/resources/mocks/mappings/post-matches/POST_match_by_court_and_case_no.json, src/test/resources/mocks/mappings/post-matches/POST_match_by_unknown_court_404.json, src/test/resources/mocks/mappings/post-matches/POST_match_server_error_500.json
Was not entirely sure where it was best that we added the call to POST  the matches.  As you can see around line 62, it happens when SearchResponse returns and at the moment, we are filtering by MatchType of ALL_SUPPLIED.
=> :sparkles: Post matches result to court case service

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml, src/main/resources/logback-spring.xml
I've broken the `instrumented` profile into two because the json logging cpability which I was hoping to use isn't yet supported by Kibana in Cloud Platform - though they are looking into it - [see this ticket](https://github.com/ministryofjustice/cloud-platform/issues/2036)
Hopefully this will follow at some point and we can just enabled the `log-json` profile and that will allow us to access fields encoded into the json directly through Kibana e.g. `json.message` or `json.log_level` rather than doing high level searches across the whole `log` field as we have to do now.
=> Log json profile

src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessor.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessorUtils.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/SourceFileNameDeserializer.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/externaldocumentrequest/Info.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/externaldocumentrequest/InfoSourceDetail.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/externaldocumentrequest/Session.java, src/main/resources/application-local.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/GatewayMessageParserTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessorUtilsTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/model/externaldocumentrequest/InfoTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapperTest.java, src/test/resources/messages/gateway-message-duplicates.xml
Rather than one document (case list for a date in a court), we end up getting a document for each time the case list gets printed. This was realised in tests, where we got 23 documents where there should only have been 4. Fixed by adding (yet) another method to the "MessageProcessorUtils". This should not happen in the strategic solution.
=> Pic 669 duplicates

build.gradle, src/main/java/uk/gov/justice/probation/courtcasematcher/CourtCaseMatcherApplication.java, src/main/java/uk/gov/justice/probation/courtcasematcher/application/MessagingConfig.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/JmsErrorHandler.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageReceiver.java, src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/application/TestMessagingConfig.java, src/test/java/uk/gov/justice/probation/courtcasematcher/controller/PingControllerTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/health/HealthCheckTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/JmsErrorHandlerTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchResponseRestClientIntTest.java
We have no persistence in Wildfly so to retain the entire message we log it at error level. Need to wrap it in an exception. When an exception is thrown by receiver then the message acknowledgement doesn't happen and it will be retried, up to the limit specified by the originating queue.
The (slight) re-wiring of the JMS beans to add JmsErrorHandler seems to have stopped the embedded broker starting. So the   Health Check test now uses a mocked JmsHealthIndicator. Also added a test for failure.
Important to say that the exception wrapping and logging of the message in the error handler are very much part of the tactical solution.
=> Local jms dlq

src/main/java/uk/gov/justice/probation/courtcasematcher/model/externaldocumentrequest/Session.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/MatcherService.java, src/test/java/uk/gov/justice/probation/courtcasematcher/model/externaldocumentrequest/SessionTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/MatcherServiceTest.java
We were matching against the court name when calling court case service - so using "Newcastle Magistrate's Court" instead of "B10JQ00" for example
=> Pic 686 match on court code

build.gradle, src/main/java/uk/gov/justice/probation/courtcasematcher/event/CourtCaseMatchEvent.java, src/main/java/uk/gov/justice/probation/courtcasematcher/event/CourtCaseSuccessEvent.java, src/main/java/uk/gov/justice/probation/courtcasematcher/event/CourtCaseUpdateEvent.java, src/main/java/uk/gov/justice/probation/courtcasematcher/event/EventListener.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessor.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/courtcaseservice/CourtCase.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapper.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/offendersearch/MatchType.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/offendersearch/SearchResponse.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClient.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/CourtCaseService.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/MatcherService.java, src/test/java/uk/gov/justice/probation/courtcasematcher/event/EventListenerTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/GatewayMessageParserTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessorTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapperTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/CourtCaseServiceTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/MatcherServiceTest.java, src/test/resources/messages/gateway-message-multi-session.xml
Two main things 
1. Support for > 1 match in the match
2. Refactoring of the service. This has a few strands
> Reduce code complexity in MatcherService. This now just returns a SearchResponse and does not deal with saving / merging cases.
> Access to WebClient is behind the services.
> Initiation of save / update / match happens from the Event Listener / Event Bus setup. MessageProcessor now just unpacks the message, and posts events to the EventBus on a case by case basis, so also has fewer responsibilities.
=> ✨ Support for > 1 match and refactoring work

src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapper.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/MatcherService.java, src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapperTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/MatcherServiceTest.java
Matcher used to apply a default status when 0 or > 1 match was found. Change so that > 1 match gives "Possible nDelius record" as the status
=> 🐛 Store "Possible nDelius record" when initial match process gives > 1 match

src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapper.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/offendersearch/SearchResponse.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/MatcherService.java, src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapperTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/model/offendersearch/SearchResponseTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchResponseRestClientIntTest.java, src/test/resources/mocks/__files/offender-search/POST_search_single_nonexact_response.json, src/test/resources/mocks/mappings/offender-search/POST_search_with_single_nonexact_match.json
Single matches with PARTIAL_NAME were being regarded as successful.
=> 🐛 Proper handling of partial / single match

src/main/java/uk/gov/justice/probation/courtcasematcher/event/EventListener.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryService.java, src/test/java/uk/gov/justice/probation/courtcasematcher/event/EventListenerTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryServiceTest.java
Added hearingDate to the matching metrics `PiCOffenderExactMatch`, `PiCOffenderPartialMatch` and `PiCOffenderNoMatch`.
Also fixed PIC-819 renaming `dateOfHearing` to `hearingDate` on `PiCCourtListReceived` and `PiCCourtCaseReceived`
=> ✨ PIC-821: Added hearingDate to the matching metrics

build.gradle, src/main/java/uk/gov/justice/probation/courtcasematcher/event/EventListener.java, src/main/java/uk/gov/justice/probation/courtcasematcher/event/OffenderSearchFailureEvent.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchRestClient.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/MatcherService.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryEventType.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryService.java, src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/event/EventListenerTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchRestClientTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/MatcherServiceTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryServiceTest.java, src/test/resources/application-test.yml
IN addition to the extra lines of code for retry, OffenderSearchRestClient  no longer has the event bus. It returns a Mono error or a searchResponse and not an empty Mono. 
The integration tests on the rest client which handle 404, 401 and so on now no longer check for an empty mono but an error with StepVerifier
Tests on the rest client which aren't relying on WireMock and therefore aren't really integration have been split out to a non-integration test.
=> ✨ PIC-822 retry mechanism for offender search

build.gradle, src/test/java/uk/gov/justice/probation/courtcasematcher/application/healthchecks/PingerTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/health/HealthCheckTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/wiremock/WiremockExtension.java, src/test/java/uk/gov/justice/probation/courtcasematcher/wiremock/WiremockMockServer.java
First part of 1096. Wanted to split it. This is just refactoring to get rid of Junit 4 which was only there to support Wiremock. There's only unit test changes here plus build.gradle.
The WiremockExtension and server were taken from community API where the same things happen.
=> ✨ Get rid of junit 4 and refactor wiremock

src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapper.java, src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapperTest.java
Allow null, do not map to some default or "Possible nDelius record". 
We will move the mapping to default in to court-case-service. court-case-matcher just passes on what it is told. So if there are multiple matches, there is no probation status so that will be null.
=> ✨ 1087 - return the probation status as-is 

.circleci/config.yml, build.gradle, src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapper.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClient.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/CourtCaseService.java, src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/pact/CourtCaseServiceConsumerPactTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/CourtCaseServiceTest.java, src/test/resources/mocks/__files/PUT_case_details_body.json, src/test/resources/mocks/__files/get-court-case/GET_court_case_response_1600028913.json, src/test/resources/mocks/__files/post-matches/POST_matches.json
Added PACT tests for - 
1. getCourtCase, the PACT only enforces the fields that are used from the CourtCaseResponse. So for example, the getCourtCase call has no interest in offences, nationality, because these values get updated with each Libra feed for the case.
2. PUT court case - uses matchers for assertions on the body of the PUT request. The interaction that the provider will verify may be a bit easier to implement. There is no interest in the response and no verification on that.
3. POST grouped offender matches - uses a literal JSON string for the assertion on the body of the POST request. There is no interest in the response and no verification on that. However, the "Location" in the response header is read and logged.
Also took the opportunity to remove the methods related to …
=> Pic 960 consumer ccs pact

helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
The error in logs was 
```org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sqsMessageReceiver': Unsatisfied dependency expressed through field 'processCourtCaseMatcherMessages'; nested exception is org.springframework.beans.TypeMismatchException: Failed to convert value of type 'java.lang.String' to required type 'boolean'; nested exception is java.lang.IllegalArgumentException: Invalid boolean value []```
There is now a boolean in the helm environment files.
=> ✨ PIC-1331 fix env vars so that the service starts

src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/Address.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/CommonPlatformHearing.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/CourtCentre.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/Defendant.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/HearingDay.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/LegalEntityDefendant.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/Offence.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/Organisation.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/PersonDefendant.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/PersonDetails.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/ProsecutionCase.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageParserTest.java, src/test/resources/messages/common-platform/hearing-invalid.json, src/test/resources/messages/common-platform/hearing.json
Just validation on this one. 
I've been reasonably strict in terms of what's required and what's not on the basis that the tighter our constraints  can be without breaking under use, the more easily we can reason about the data we're receiving. If validation fails when we start integration testing with CP then a) we've learned something and b) it's trivial to relax any constraints that aren't strictly needed.
Anything marked as required in the schema is obviously mandatory. In addition to this anything that is required or expected in the court-case-service is required. I've also made all ids @NotBlank on the basis that they *should* always be present and if we hang on to these for future use then we will probably need them to be present.
=> ✨️ PIC-1689: Add validation for CommonPlatformHearing

src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/HearingProcessor.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryEventType.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryService.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/HearingProcessorTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryServiceTest.java, src/test/resources/mocks/mappings/post-matches/POST_match_by_case_and_defendant_id.json, src/test/resources/mocks/mappings/post-matches/POST_match_by_case_and_defendant_id_any_other.json
The main reason for this change is to fix a number of integration tests which were erroneously passing when exceptions being thrown. It will prevent future cases of this and as a bonus allows better visibility of processing errors in AppInsights
=> 🔊 PIC-2477: Emit processing failure telemetry events

helm_deploy/court-case-matcher/Chart.yaml, helm_deploy/court-case-matcher/templates/requirements.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
This was significantly complicated by the fact that this service is on helm v1, and does not already have alerting or the generic service set up.
=> PIC-4008 add prometheus alerting on SQS

helm_deploy/court-case-matcher/Chart.yaml, helm_deploy/court-case-matcher/templates/requirements.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
This reverts commit 1b4b70099258805a78bfe884b9a6905080a6cd13.
Failed to deploy unfortunately.
Suggested course is to upgrade charts to helm v2 and use the generic-service helm chart before attempting this again
=> Revert "PIC-4008 add prometheus alerting on SQS (#629)"

build.gradle
remove unused app insights dependencies after we included `uk.gov.justice.hmpps.gradle-spring-boot`
Remove agentDeps as this is brought in by `uk.gov.justice.hmpps.gradle-spring-boot`
Hopefully resolving this error 
` ERROR c.m.applicationinsights.agent - Application Insights Java Agent 3.4.10 startup failed (PID 1)`
=> PIC-4145 Remove unused app insights dependencies

src/main/java/uk/gov/justice/probation/courtcasematcher/service/ReplayHearingsService.java
Add an hour to the hearing timestamp we get from the csv
This is because the court-case-service hearing.lastUpdated date is using BST UK timezone.
In order to compare the CSV hearing timestamp to ccs hearing we need to make both dates BST
=> PIC-4207 Update UTC date to BST+1

helm_deploy/court-case-matcher/templates/ingress.yaml, src/main/java/uk/gov/justice/probation/courtcasematcher/service/ReplayHearingsService.java
Deny requests to /replay404Hearings on the ingress
Update ingress to block `/queue-admin/retry-all-dlqs` calls
Move log into the finally block of try/catch
=> PIC-4207 Deny requests to 404hearings

build.gradle
Removed the dependencies which spring is already bringing in at 2.17.2
=> FIX: set jackson-dataformat-xml to the same jackson version as the other dependencies which are brought in by spring

Dockerfile
Build gradle in the Dockerfile. This unblocks usage of hmpps circleci orb for build_docker
Use multi-stage Dockerfile to build Gradle first
=> PIC-4150 Build gradle and use multi-stage dockerfile

src/main/java/uk/gov/justice/probation/courtcasematcher/security/OAuth2SecurityConfig.java, src/main/resources/application-local.yml, src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/application/TestMessagingConfig.java, src/test/java/uk/gov/justice/probation/courtcasematcher/info/InfoTest.java
Enable `/info` endpoint
Allow public access to info endpoint
This will reduce errors on court-case-matcher which was called by the [developer-portal](https://developer-portal.hmpps.service.justice.gov.uk/components/court-case-matcher/environment/dev)
=> PIC-4243 Enable info endpoint

src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/model/offendersearch/MatchRequest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/MatcherServiceTest.java
Set the defendant date of birth to null if it is not in the past
This fixes a failure when calling the offender search api that requires the defendant dob to be in the past or it'll return a 400 BAD Request error. We have a FIFO event driven architecture so 1 message stuck on the queue leads to a blockage.
See here https://github.com/ministryofjustice/probation-offender-search/blob/69396dc73e71921848b499205689ab24610f25f0/src/main/kotlin/uk/gov/justice/hmpps/probationsearch/dto/MatchRequest.kt#L13
=> PIC-4522 Set DOB to null if not in past
