ministryofjustice/court-case-matcher

README.md
Change to README to describe how to run the crime portal mirror gateway
=> Pic 532 run ccm

src/main/java/uk/gov/justice/probation/courtcasematcher/model/externaldocumentrequest/Case.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/externaldocumentrequest/Name.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/externaldocumentrequest/Session.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapper.java, src/main/resources/application-local.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/GatewayMessageParserTest.java, src/test/resources/messages/gateway-message-full.xml, src/test/resources/messages/gateway-message-single-case.xml
I have also added a Name object which has the "def_name" field split up. Also ou_code. Don't think either of these will be used just yet but we have tickets for both on the backlog
=> :sparkles: Now have PNC / CRO and name and ou_code

helm_deploy/court-case-matcher/templates/_envs.tpl, src/main/resources/application-dev.yml, src/main/resources/application-local.yml, src/main/resources/application.yml
Using new secret references and hostname for JMS queue
=> Add deployment secrets

src/main/resources/application-dev.yml, src/main/resources/application-local.yml
Should give us more info about how spring is handling the JMS connection
=>  extend actuator and logging for startup

src/main/resources/application-dev.yml
small change to use service for the hostname in dev namespace
=> :wrench: restore GATEWAY_JMS_HOST

src/main/resources/application-preprod.yml
=> :wrench: Make CCS endpoint https not http

src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/event/EventListenerTest.java
=> Add app name

src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessorUtils.java
Added logging for de-duplicated messages, when it happens.  Realised we'd have no way of seeing the result.
=> 📣 added log statement for messages after de-duplication

build.gradle, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessor.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessorUtils.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessorUtilsTest.java
In the tactical solution we have no current way in tactical solution of identifying the document which is the actual one which we need.
=> ✨ No longer de-duplicate 

build.gradle, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessor.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessorTest.java
We'll just  log a message when each court is completed
=> ⚡️ Removed case removal for tactical solution

build.gradle, src/main/java/uk/gov/justice/probation/courtcasematcher/model/externaldocumentrequest/Case.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapper.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/GatewayMessageParserTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClientIntTest.java, src/test/resources/messages/gateway-message-multi-session.xml, src/test/resources/messages/gateway-message-single-case.xml
nationality 1 and 2 were re-added to payload after the XSD was removed
=> ✨ Add in nationality 1 and 2 capture from payload

src/main/java/uk/gov/justice/probation/courtcasematcher/application/TelemetryConfig.java, src/main/java/uk/gov/justice/probation/courtcasematcher/event/EventListener.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessor.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageReceiver.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/offendersearch/SearchResponse.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/MatcherService.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryEventType.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryService.java, src/test/java/uk/gov/justice/probation/courtcasematcher/event/EventListenerTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageProcessorTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageReceiverTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/MatcherServiceTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryServiceTest.java
Followed the court case service example (minus request based properties for user / client).
=> ✨ Added App Insights telemetry for calls as defined in ticket 743

src/main/java/uk/gov/justice/probation/courtcasematcher/event/EventListener.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/NameHelper.java, src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/event/EventListenerTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/NameHelperTest.java
Also removed the success and failure counts from EventListener - they weren't really used and weren't telling us anything meaningful
=> ✨ PIC-874 Remove title from search name being passed

src/main/java/uk/gov/justice/probation/courtcasematcher/event/EventListener.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClient.java
=> 👌🏻 QA - logging and ensure offender matches are posted

Dockerfile, applicationinsights.json, build.gradle, run.sh, src/main/resources/application-instrumented.yml
Disclaimer: as with the court-case-service I haven't managed to get telemetry from my local machine to azure in dev. Rather than waste any more time trying to debug locally I'd like to merge to main and see if it works. It shouldn't break anything as even if the agent fails to start the application will so worst case scenario is that it just doesn't work and I have to roll back or fix forward
=> 📈 PIC-900 - Add application insights agent

src/main/java/uk/gov/justice/probation/courtcasematcher/CourtCaseMatcherApplication.java, src/main/java/uk/gov/justice/probation/courtcasematcher/application/healthchecks/SqsCheck.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/SqsService.java, src/main/resources/application-dev.yml, src/main/resources/application.yml
=> 🐛 PIC-932 Ensure SQS is not included in health check when it is off

helm_deploy/court-case-matcher/templates/deployment.yaml, helm_deploy/court-case-matcher/templates/hpa.yaml, helm_deploy/values-dev.yaml, helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
min 1, max 2 pods on dev and pre prod
min 2, max 3 on prod
=> 🔧 PIC-1127 auto scale pods

README.md, src/main/java/uk/gov/justice/probation/courtcasematcher/application/FeatureFlags.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/courtcaseservice/CourtCase.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/courtcaseservice/ProbationStatusDetail.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapper.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/MatchDetails.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/offendersearch/ProbationStatus.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/offendersearch/SearchResponse.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClient.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchRestClient.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/CourtCaseService.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/MatcherService.java, src/test/java/uk/gov/justice/probation/courtcasematcher/application/FeatureFlagsTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapperTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/MatcherServiceTest.java, src/test/resources/application-test.yml, src/test/resources/mocks/__files/offender-search/POST_search_single_exact_response.json, src/test/resources/mocks/mappings/get-probation-status-detail/GET_probation_status_detail_by_crn.json
This is behind a flag (`use-offender-search-for-probation-status` ), defaulting to false until offender search has been updated.
=> ✨use offender search for probation status.

.circleci/config.yml, build.gradle, src/test/java/uk/gov/justice/probation/courtcasematcher/pact/CourtCaseServiceConsumerPactTest.java
Added consumerVersion which will always be main based on current thinking. We'll just publish the PACT off work committed to main, then provider will check against that.
=> Pic 960 fix pact version

src/main/java/uk/gov/justice/probation/courtcasematcher/event/EventListener.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClient.java
Need some extra detail when the save fails. Also remove name from one of the logs.
=> ✨ PIC-1320 - improve logging for failed saves

src/main/resources/application.yml
=> ✨ PIC-1352 read timeout increase

helm_deploy/court-case-matcher/templates/_envs.tpl, src/main/java/uk/gov/justice/probation/courtcasematcher/application/SqsMessagingConfig.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsMessageReceiverIntTest.java, src/test/resources/application-test.yml
Sorry - stuffed up the _envs.tpl on last one
=> ✨ PIC-1331 fix env vars so that the service starts

.circleci/config.yml, doc/adr/0001-record-architecture-decisions.md, doc/adr/0002-retain-and-process-sns-metadata.md, docker-compose.yml, src/main/java/uk/gov/justice/probation/courtcasematcher/application/MessagingConfig.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/CaseMessageProcessor.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageParser.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/MqMessageReceiver.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsCpgMessageReceiver.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsMessageReceiver.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/SnsMessageContainer.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClient.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryEventType.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryService.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/CaseMessageProcessorTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/MqMessageReceiverTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsCpgMessageReceiverIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsCpgMessageReceiverTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsMessageReceiverIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsMessageReceiverTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/TelemetryServiceTest.java, src/test/resources/application-test.yml, src/test/resources/localstack/setup-sqs.sh, src/test/resources/messages/json/case-sns-metadata-invalid.json, src/test/resources/messages/json/case-sns-metadata.json
Use SNS in integration tests and handle the message metadata associated with SNS->SQS
=> Pic 1331 msg metadata handle

src/main/java/uk/gov/justice/probation/courtcasematcher/model/courtcaseservice/CourtCase.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/courtcaseservice/ProbationStatusDetail.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapper.java, src/test/java/uk/gov/justice/probation/courtcasematcher/model/mapper/CaseMapperTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/OffenderSearchRestClientIntTest.java, src/test/resources/mocks/__files/offender-match/POST_match_single_exact_response.json, src/test/resources/mocks/__files/offender-search/POST_search_with_multiple_responses.json, src/test/resources/mocks/__files/offender-search/POST_search_with_response.json
Adding support awaitingPsr in CCM when a match is done on a new case, and searching to update when a case is already matched.
=> ✨ PIC-1429 support for awaitingPsr

helm_deploy/values-dev.yaml
Signed-off-by: katie-cawthorne <katie.cawthorne@digital.justice.gov.uk>
=> :wrench: PIC-1515: apply cpu and memory limits for dev

src/main/java/uk/gov/justice/probation/courtcasematcher/model/domain/CourtCase.java, src/main/java/uk/gov/justice/probation/courtcasematcher/repository/CourtCaseRepository.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClient.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseServiceRestHelper.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/LegacyCourtCaseRestClient.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/CourtCaseService.java, src/main/resources/application.yml, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/LegacyCourtCaseRestClientIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/CourtCaseServiceTest.java, src/test/resources/mocks/mappings/post-matches/POST_match_by_case_and_defendant_id.json, src/test/resources/mocks/mappings/post-matches/POST_match_server_error_500_case_id.json
Instead of posting by court code and case no
=> ✨ PIC-1716 - post offender matches by case id and defendant id

src/main/java/uk/gov/justice/probation/courtcasematcher/application/MessagingConfig.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/CourtCaseExtractor.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/CPHearingEvent.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/CourtCaseExtractorTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/MessageParserTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsMessageReceiverIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/CPHearingEventTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/CPHearingTest.java, src/test/resources/messages/common-platform/hearing-invalid.json, src/test/resources/messages/common-platform/hearing-with-legal-entity-defendant.json, src/test/resources/messages/common-platform/hearing.json
The JSON files did not match those in CHER, or what we received in the connectivity test
=> ð  PIC-1755 - fix JSON files for message to reflect connectivity test

src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/model/courtcaseservice/CCSDefendant.java, src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/model/courtcaseservice/CCSPhoneNumber.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/model/courtcaseservice/CCSDefendantTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/model/courtcaseservice/CCSPhoneNumberTest.java
. Added tests to verify the behaviour.
=> . mapped phone number details back to defendant.

src/main/java/uk/gov/justice/probation/courtcasematcher/service/CourtCaseService.java, src/test/java/uk/gov/justice/probation/courtcasematcher/service/CourtCaseServiceTest.java
. Logged the thrown exception.
. Refactored code not to call post offender matches if save court case failed.
=> . Updated the code to handle exception when save court case failed.

src/main/resources/application-prod.yml
This reverts commit bd3188fc22ca5046df45a122b6ad716517d96b44.
=> Revert "PIC-2293 enable heairng by list number (#512)"

helm_deploy/values-preprod.yaml, helm_deploy/values-prod.yaml
- Increase Java maximum heap size
- Increase k8s pod memory resources
=> PIC-3280 Increase Java heap size

src/main/java/uk/gov/justice/probation/courtcasematcher/service/ReplayHearingsService.java
Move try/catch inside for loop and add more logging information
=> PIC-4207: Move try/catch inside for loop

src/main/java/uk/gov/justice/probation/courtcasematcher/controller/Replay404HearingsController.java, src/main/java/uk/gov/justice/probation/courtcasematcher/service/ReplayHearingsService.java, src/test/java/uk/gov/justice/probation/courtcasematcher/controller/Replay404HearingsControllerIntTest.java
Fix and enable test
remove if statement around log
=> PIC-4207 Fix and enable test

src/main/java/uk/gov/justice/probation/courtcasematcher/service/ReplayHearingsService.java, src/test/resources/replay404hearings/README.md
Update README and set curl to have -F flag before posting a file
Update azure log to use the custom event name
=> PIC-4207 Update README and Azure log

helm_deploy/court-case-matcher/templates/_envs.tpl, helm_deploy/court-case-matcher/templates/housekeeping-cronjob.yaml
This reverts commit cc4bf2d496715509fa6be99db973b7e6d4910a55.
=> PIC-4207 re-enable message processing following data recovery

src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsMessageReceiver.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/CPDefendant.java, src/main/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/CPHearing.java, src/main/java/uk/gov/justice/probation/courtcasematcher/model/domain/Hearing.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsMessageReceiverIntTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/SqsMessageReceiverTest.java, src/test/java/uk/gov/justice/probation/courtcasematcher/messaging/model/commonplatform/CPDefendantTest.java, src/test/resources/messages/common-platform/youthDefendantHearing.json
=> PIC-4200 (#649)

src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/CourtCaseServiceClient.java
Fix log message when failing to get a hearing from court case service
=> Fix logging message

src/test/resources/replay404hearings/README.md
Update replay404Hearings README:
> There is a significant risk of overwriting data, if you decide to use this process. The more time passes before recovering data, the more likely data could be overwritten when running this replay404Hearings.
> This is because the court-case-service does not accurately report the last_updated date of the hearing.
knowing if a hearing has been updated recently is a difficult task to do in court-case-service due to a highly normalized database. `hearing.last_updated` date will not show if the `hearing.hearings_days` has been updated more recently.
=> Update the README to warn about using replay404Hearings

.circleci/config.yml
Use the [hmpps circleci orb](https://circleci.com/developer/orbs/orb/ministryofjustice/hmpps) to deploy to environments
Remove custom code that is already being done by the above orb.
Send slack notification when prod has released (ignore this for preprod and dev)
=> PIC-4150 Use HMPPS CircleCi Orb

.circleci/config.yml
Use build_docker from HMPPS CircleCi Orb
=> PIC-4150 Use build_docker from HMPPS CircleCi Orb

src/test/resources/replay404hearings/README.md
Warn that replay404Hearings works on ConfirmOrUpdated hearing updates not Resulted etc.
=> Warn that replay404Hearings works on confirmorupdated hearing updates

src/main/java/uk/gov/justice/probation/courtcasematcher/application/WebConfig.java, src/main/resources/application.yml
Reverts ministryofjustice/court-case-matcher#683
=> Revert "Fix connection issues with reactor"

src/main/java/uk/gov/justice/probation/courtcasematcher/restclient/LegacyCourtCaseRestClient.java, src/test/java/uk/gov/justice/probation/courtcasematcher/restclient/LegacyCourtCaseRestClientIntTest.java, src/test/resources/mocks/mappings/get-case/GET_case_details_by_list_no_404.json, src/test/resources/mocks/mappings/get-case/GET_case_details_by_list_no_500.json
Ensure only 404 results in a new LIBRA hearing and case being crated in CCS
=> PIC-4476: Ensure only 404 results in a new LIBRA hearing and case being crated in CCS

helm_deploy/court-case-matcher/values.yaml
this is so that i can easily add test data via CHER to court-case-service
=> temp undo queue switch for testing
